import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

const noto_sans_thai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  weight: ["400", "500", "700", "900"],
  subsets: ["latin", "thai"],
  style: "normal",
});


export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${noto_sans_thai.variable}`}
      >
          {children}
      </body>
    </html>
  );
}
